# Generated by Django 2.0.5 on 2018-05-10 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('objetivo_pedagogico', models.TextField(verbose_name='Objetivo Pegagogico')),
                ('atividades', models.TextField(verbose_name='Atividades')),
                ('metodologia', models.TextField(verbose_name='Metodologia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estrutura Digital Pedagógica',
                'verbose_name_plural': 'Estruturas Digitais Pedagógicas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='RecursosEdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_embedded', models.TextField(blank=True, verbose_name='Video embedded')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
                ('recebe_texto', models.BooleanField(default=False, verbose_name='Responder texto ?')),
                ('recebe_video_embedded', models.BooleanField(default=False, verbose_name='Responder com videos do youtube?')),
                ('recebe_video', models.BooleanField(default=False, verbose_name='Responder com video?')),
                ('recebe_imagem', models.BooleanField(default=False, verbose_name='Responder com imagem ?')),
                ('edp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edps', to='edp.Edp', verbose_name='Edp')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='edp.Turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('usuario', 'turma')},
        ),
    ]
