# Generated by Django 2.0.4 on 2018-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('objetivo_pedagogigo', models.TextField()),
                ('atividades', models.TextField(verbose_name='Atividades')),
                ('metodologia', models.TextField(verbose_name='Metodologia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Estrutura Digital Pedagógica',
                'verbose_name_plural': 'Estruturas Digitais Pedagógicas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
