# Generated by Django 2.0.5 on 2018-07-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='texto',
        ),
    ]
