# Generated by Django 2.0.5 on 2018-07-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaedp',
            name='texto2',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
    ]
