# Generated by Django 2.0.5 on 2018-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edp',
            name='habilidades',
            field=models.ManyToManyField(related_name='habilidade_edp', to='edp.Habilidade'),
        ),
    ]
