# Generated by Django 2.0.5 on 2018-06-01 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0002_edp_habilidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaEdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_embedded', models.TextField(blank=True, verbose_name='Video embedded')),
                ('texto', models.TextField(blank=True, verbose_name='Texto')),
                ('edp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='edp.Edp', verbose_name='Edp')),
            ],
        ),
    ]
