# Generated by Django 2.0.4 on 2018-04-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0002_auto_20180417_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edp',
            old_name='objetivo_pedagogigo',
            new_name='objetivo_pedagogico',
        ),
    ]
