# Generated by Django 2.0.5 on 2018-07-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0003_respostaedp_aluno2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaedp',
            name='aluno2',
        ),
        migrations.RemoveField(
            model_name='respostaedp',
            name='texto2',
        ),
    ]
