# Generated by Django 2.0.5 on 2018-06-03 19:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0003_respostaedp'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('video', models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\raiss\\Documents\\Projetos\\adaple-restruturado\\projeto\\static'), upload_to='media/videosenviados')),
            ],
        ),
    ]
