# Generated by Django 2.0.4 on 2018-04-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0004_auto_20180418_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosEdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_embedded', models.TextField(blank=True, verbose_name='Video embedded')),
                ('text', models.TextField(blank=True, verbose_name='Texto')),
                ('recebe_texto', models.BooleanField(default=False, verbose_name='Responder texto ?')),
                ('recebe_video_embedded', models.BooleanField(default=False, verbose_name='Responder com videos do youtube?')),
                ('recebe_video', models.BooleanField(default=False, verbose_name='Responder com video?')),
                ('recebe_imagem', models.BooleanField(default=False, verbose_name='Responder com imagem ?')),
                ('edp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edps', to='edp.Edp', verbose_name='Edp')),
            ],
        ),
    ]
