# Generated by Django 2.0.5 on 2018-06-03 20:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0004_db_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursosedp',
            name='video',
            field=models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\raiss\\Documents\\Projetos\\adaple-restruturado\\projeto\\static'), upload_to='media/videosenviados'),
        ),
        migrations.AddField(
            model_name='respostaedp',
            name='video',
            field=models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\raiss\\Documents\\Projetos\\adaple-restruturado\\projeto\\static'), upload_to='media/videosenviados'),
        ),
    ]
