# Generated by Django 2.0.5 on 2018-07-12 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0004_auto_20180712_0159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='recursosedp',
            name='edp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='edp.Edp', verbose_name='Edp'),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
