# Generated by Django 2.0.5 on 2018-07-17 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edp', '0004_auto_20180717_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaedp',
            name='aprendiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL, verbose_name='aluno'),
            preserve_default=False,
        ),
    ]
