# Generated by Django 2.0.5 on 2018-07-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0005_respostaedp_aprendiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaedp',
            name='aprendiz',
        ),
    ]
