# Generated by Django 2.0.4 on 2018-04-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0005_recursosedp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recursosedp',
            old_name='text',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='name',
            new_name='nome',
        ),
    ]
