# Generated by Django 2.0.4 on 2018-04-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0006_auto_20180418_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='edp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edps', to='edp.Edp', verbose_name='Edp'),
        ),
    ]
