# Generated by Django 2.0.5 on 2018-07-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_assuntos'),
        ('edp', '0006_remove_respostaedp_aprendiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaedp',
            name='aprendiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respostaAprendiz', to='accounts.Student', verbose_name='aprendiz '),
            preserve_default=False,
        ),
    ]
