# Generated by Django 2.0.5 on 2018-06-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0007_auto_20180604_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edp',
            name='habilidade_audicao',
        ),
        migrations.RemoveField(
            model_name='edp',
            name='habilidade_escrita',
        ),
        migrations.RemoveField(
            model_name='edp',
            name='habilidade_fala',
        ),
        migrations.RemoveField(
            model_name='edp',
            name='habilidade_leitura',
        ),
        migrations.RemoveField(
            model_name='edp',
            name='habilidade_traducao',
        ),
    ]
