# Generated by Django 2.0.6 on 2018-08-16 12:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0008_auto_20180717_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='video',
            field=models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='/home/adalin/adaple-restruturado/projeto/static'), upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='respostaedp',
            name='video',
            field=models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='/home/adalin/adaple-restruturado/projeto/static'), upload_to='video/'),
        ),
    ]
