# Generated by Django 2.0.5 on 2018-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0008_auto_20180604_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='edp',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=1, verbose_name='Situação'),
        ),
    ]
