# Generated by Django 2.0.5 on 2018-10-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0008_auto_20180717_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostaedp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resposta Estrutura Digital de Aprendizagem', 'verbose_name_plural': 'Resposta Estrutura Digital de Aprendizagem'},
        ),
    ]
