# Generated by Django 2.0.5 on 2018-06-04 21:03

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0009_edp_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='video_embedded',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respostaedp',
            name='video_embedded',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
