# Generated by Django 2.0.5 on 2018-11-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0009_auto_20181026_1224'),
        ('edp', '0009_auto_20180816_0938'),
    ]

    operations = [
    ]
