# Generated by Django 2.0.5 on 2018-06-13 01:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0010_auto_20180604_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edp',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(0, 'Iniciante'), (1, 'Básico'), (2, 'Proficiente'), (3, 'Avançado'), (4, 'Fluente')], default=1, verbose_name='Nível de proficiência'),
        ),
        migrations.AlterField(
            model_name='recursosedp',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
    ]
