# Generated by Django 2.0.5 on 2018-06-13 01:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0011_auto_20180612_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
