# Generated by Django 2.0.5 on 2018-06-20 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0012_auto_20180612_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edp',
            options={'ordering': ['created_at'], 'verbose_name': 'Estrutura Digital de Aprendizagem', 'verbose_name_plural': 'Estruturas Digital de Aprendizagem'},
        ),
        migrations.AlterModelOptions(
            name='recursosedp',
            options={'ordering': ['created_at'], 'verbose_name': 'Recurso Estrutura Digital de Aprendizagem', 'verbose_name_plural': 'Recursos Estruturas  Digital de Aprendizagem'},
        ),
        migrations.AlterModelOptions(
            name='respostaedp',
            options={'ordering': ['edp'], 'verbose_name': 'Resposta Estrutura Digital de Aprendizagem', 'verbose_name_plural': 'Resposta Estrutura Digital de Aprendizagem'},
        ),
        migrations.AddField(
            model_name='recursosedp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recursosedp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='respostaedp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostaedp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
