# Generated by Django 2.0.5 on 2018-06-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0013_auto_20180620_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
    ]
