# Generated by Django 2.0.5 on 2018-06-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0014_auto_20180623_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='edp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edps', to='edp.Edp', verbose_name='Edp'),
        ),
    ]
