# Generated by Django 2.0.5 on 2018-06-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0016_auto_20180625_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursosedp',
            name='edp',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='edp.Edp', verbose_name='Edp'),
        ),
    ]
