# Generated by Django 2.0.5 on 2018-06-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0018_auto_20180625_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edp',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(0, 'Básico (Sem certifacação)'), (1, 'Intermediário'), (2, 'Intermediário Superior'), (3, 'Avançado'), (4, 'Avançado Superior')], default=1, verbose_name='Nível de proficiência'),
        ),
        migrations.AlterField(
            model_name='recursosedp',
            name='edp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='edp.Edp', verbose_name='Edp'),
        ),
    ]
