# Generated by Django 2.0.5 on 2018-06-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0019_auto_20180630_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edp',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(0, 'Básico (Sem certificação)'), (1, 'Intermediário'), (2, 'Intermediário Superior'), (3, 'Avançado'), (4, 'Avançado Superior')], default=1, verbose_name='Nível de proficiência'),
        ),
    ]
