# Generated by Django 2.0.5 on 2018-06-30 18:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0020_auto_20180630_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\raiss\\Documents\\Projetos\\adaple-restruturado\\projeto\\static'), upload_to='media/videosenviados')),
            ],
        ),
        migrations.DeleteModel(
            name='db_video',
        ),
        migrations.RenameField(
            model_name='respostaedp',
            old_name='video',
            new_name='Video_resposta',
        ),
        migrations.AddField(
            model_name='video',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='edp.RespostaEdp', verbose_name='Video_resposta'),
        ),
    ]
