# Generated by Django 2.0.5 on 2018-06-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edp', '0021_auto_20180630_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostaedp',
            old_name='Video_resposta',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='resposta',
        ),
    ]
