# Generated by Django 2.0.5 on 2018-05-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='eh_aluno',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='eh_professor',
        ),
    ]
