# Generated by Django 2.0.5 on 2018-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180510_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='assuntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='a',
        ),
        migrations.AddField(
            model_name='student',
            name='a',
            field=models.ManyToManyField(related_name='a_assuntos', to='accounts.assuntos'),
        ),
    ]
