# Generated by Django 2.0.5 on 2018-05-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180510_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='a',
        ),
    ]
