# Generated by Django 2.0.5 on 2018-07-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assuntos',
        ),
    ]
